---
- name: Installing APT Packages
  ansible.builtin.apt:
    deb: "{{ item }}"
    state: present
    force: true
    fail_on_autoremove: true
  loop: "{{ packages.deb_packages }}"
  when: packages.deb_packages is defined
  