---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: packages
    image: jrei/systemd-ubuntu:22.04
    extra_packages:
      - apt-transport-https
      - sudo
      - gpg-agent
    tmpfs:
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp:/tmp:rw
      - /temporario:/temporario:rw
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    # pre_build_image: true
    published_ports:
      - 6001/tcp
provisioner:
  name: ansible
